apiVersion: v1
kind: ReplicationController
metadata:
  name: ${BLUEGREEN}
  labels:
    app: ${BLUEGREEN}
spec:
  replicas: 2
  selector:
    app: ${BLUEGREEN}
  template:
    metadata:
      name: ${BLUEGREEN}
      labels:
        app: ${BLUEGREEN}
    spec:
      containers:
      - name: ${BLUEGREEN}
        image: "${DOCKER_USERNAME}/${IMAGE_NAME}:${BUILD_ID}"
        ports:
        - containerPort: 80